<a href="https://colab.research.google.com/github/ticoabc/bootcampPreparaTech/blob/main/Aula18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Aula 18 - Franciane Rodrigues**
##**Python para Análise de Dados**

Escola: SoulCode Academy

Curso: PreparaTech - AD4

Assunto: Projeto de ETL e Análise de Dados

Professor(a): Franciane Rodrigues

Aluno(a): Tiago de Freitas

## **Estatística Descritiva**

As estatísticas descritivas envolvem os métodos usados para resumir, simplificar e descrever os principais recursos de um conjunto de dados.

Este ramo da estatística visa fornecer uma visão geral concisa e significativa dos dados por meio de medidas de tendência central (média, mediana, moda), dispersão (intervalos, variância, desvio-padrão) e representação gráfica, tais como histogramas, gráfico de barras, gráfico de setores, gráficos de dispersão e etc.


As estatísticas descritivas nos ajudam a compreender as caracteristicas fundamentais de um conjunto de dados e torná-lo mais gerenciável para análise.

## **Solicitação**

Realize uma análise exploratória de dados (EDA) usando estatistica descritiva para obter informações úteis sobre o programa Desenrola.

In [1]:
# Importando a biblioteca
import pandas as pd

In [18]:
# Configurando a quantidade de colunas para aparecer e m um dataframe
pd.set_option('display.max_columns',100)

*   **Tipos de separador:** Vírgula (,) - Ponto e vírgula (;) - Tabulação (\t) - Espaço em branco ( )
*   **Enconding:** UTF-8, ISO-8859-1, UTF-16, UTF-32, ASCII

In [17]:
# Extração por Google Drive
# Favor testar os separadores e encodings para outras bases de dados, caso necessário
df = pd.read_csv('/content/dados_desenrola.csv',
                 sep=';',
                 encoding='UTF-8')

In [ ]:
# Verificação de extração dos dados
df

## **Pré-análise**

In [ ]:
# Visualizando o dataframe
df

In [ ]:
# Visualizando os dados começando pelo cabeçalho
df.head()

In [ ]:
# Visualizando as últimas posições do dataframe
df.tail()

In [ ]:
# Visualização do dataframe de forma aleatoria
df.sample(5)

In [24]:
# Verificando o tamanho do dataframe (linhas, colunas)
df.shape

(2104, 7)

In [25]:
# Verificação do tipo de dados de uma coluna
df.dtypes

DATA_BASE                        int64
FAIXA_DESENROLA                  int64
UNIDADE_FEDERACAO               object
COD_CONGLOMERADO_FINANCEIRO      int64
NOME_CONGLOMERADO_FINANCEIRO    object
NUMERO_OPERACOES                 int64
VOLUME_OPERACOES                object
dtype: object

In [26]:
# Vamos contar quantas observações temos em cada coluna
df.count()

DATA_BASE                       2104
FAIXA_DESENROLA                 2104
UNIDADE_FEDERACAO               2104
COD_CONGLOMERADO_FINANCEIRO     2104
NOME_CONGLOMERADO_FINANCEIRO    2104
NUMERO_OPERACOES                2104
VOLUME_OPERACOES                2104
dtype: int64

In [ ]:
# Informações detalhadas do dataframe
df.info()

In [77]:
# Bônus: verificando o nome das colunas
df.columns

Index(['data_base', 'faixa', 'uf', 'nome', 'qtd_operacoes', 'vol_operacoes'], dtype='object')

###Com a fase de Pré-visualização dos dados responda algumas perguntas gerais:###

* Qual das colunas são importantes na sua opinião?
* Qual das colunas poderão ser retiradas da sua análise?
* Há colunas iguais?
* Há linhas iguais?
* Os valores são unicos em uma coluna?
* Há alguma inconsistência nas colunas?
* Há valores nulos?
* Precisa renomear as colunas?
* Precisa renomear os dados categóricos?
* Os tipos de dados estão adequados nas colunas?

## **Transformação dos dados**

Verificações gerais e básicas de qualquer transformação em bases de dados, se houver os casos abaixo:

*  Escolher as possiveis colunas importantes para análise
*  Verificar se há colunas iguais
*  Verificar e tratar valores (observações) únicas
*  Verificar e tratar valores duplicados
*  Verificar e tratar as inconsistências (linguagem, escrita com caracteres, espaços e etc.)
*  Verificar e tratar valores nulos
*  Tradução/Renomear
*  Transformação dos tipos adequados dos dados
*  Esse é obrigatório como sendo último: Garantir a qualidade e integridade dos dados.

In [76]:
# Visualização da base de dados
df.sample(5)

,data_base,faixa,uf,nome,qtd_operacoes,vol_operacoes
881,202311,1,BA,BTG PACTUAL,1838,"2036566,87"
2093,202312,2,SP,CAIXA ECONÔMICA FEDERAL,1530,"2614272,78"
389,202310,1,MT,NUBANK,1108,"797323,59"
1375,202311,2,PI,ITAU,89,"248024,33"
2101,202312,2,TO,CAIXA ECONÔMICA FEDERAL,55,"98061,03"

###Tradução/Renomear###

In [58]:
# Renomeando colunas para tradução
df.rename(columns={'DATA_BASE': 'data_base',
                   'FAIXA_DESENROLA': 'faixa',
                   'UNIDADE_FEDERACAO':'uf',
                   'COD_CONGLOMERADO_FINANCEIRO': 'cod_cng_fin',
                   'NOME_CONGLOMERADO_FINANCEIRO': 'nome_inst_fin',
                   'NUMERO_OPERACOES': 'qtd_operacoes',
                   'VOLUME_OPERACOES': 'vol_operacoes',
                   }, inplace=True)

In [69]:
# Checando alteração
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2104 entries, 0 to 2103
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   data_base      2104 non-null   int64
 1   faixa          2104 non-null   int64
 2   uf             2104 non-null   object
 3   nome           2104 non-null   object
 4   qtd_operacoes  2104 non-null   int64
 5   vol_operacoes  2104 non-null   object
dtypes: int64(3), object(3)
memory usage: 98.8+ KB

In [70]:
# Modo 1: verificando valores nulos
df.isna().sum()

data_base        0
faixa            0
uf               0
nome             0
qtd_operacoes    0
vol_operacoes    0
dtype: int64

In [71]:
# Modo 2: verificando valores nulos
df.isnull().sum()

data_base        0
faixa            0
uf               0
nome             0
qtd_operacoes    0
vol_operacoes    0
dtype: int64

In [72]:
# Modo 3: Calcular a porcentagem de valores nulos em cada coluna
porcentagem_nulos = (df.isnull().sum() / len(df)) * 100

# Exibir a porcentagem de valores nulos em cada coluna
print(round(porcentagem_nulos,1))

data_base        0.0
faixa            0.0
uf               0.0
nome             0.0
qtd_operacoes    0.0
vol_operacoes    0.0
dtype: float64

In [73]:
# Removendo linhas com valores NaN
df = df.dropna()

In [74]:
# Checagem se de fato os valores nulos foram eliminados
df.isna().sum()

data_base        0
faixa            0
uf               0
nome             0
qtd_operacoes    0
vol_operacoes    0
dtype: int64

In [75]:
# Comando para verificar o balanceamento do dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2104 entries, 0 to 2103
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   data_base      2104 non-null   int64
 1   faixa          2104 non-null   int64
 2   uf             2104 non-null   object
 3   nome           2104 non-null   object
 4   qtd_operacoes  2104 non-null   int64
 5   vol_operacoes  2104 non-null   object
dtypes: int64(3), object(3)
memory usage: 98.8+ KB

### Verificando se os dados são unicos na coluna
> Se a resposta for True: os valores são unicos

> Se a resposta for False: os valores não são unicos

In [43]:
df.uf.is_unique

False

### Modo 1: Encontrando as linhas duplicadas com base na coluna###

In [42]:
df[df.duplicated(subset='uf', keep=False)]

,DATA_BASE,faixa,uf,cod_cng_fin,nome,qtd_operacoes,vol_operacoes
0,202309,2,AC,49906,BB,143,"1424098,33"
1,202309,2,AC,10045,BRADESCO,16,"110040,84"
2,202309,2,AC,49944,BTG PACTUAL,7,"37788,79"
3,202309,2,AC,51626,CAIXA ECONÔMICA FEDERAL,83,"248219,50"
4,202309,2,AC,51884,INTER,5,"16763,18"
...,...,...,...,...,...,...,...
2099,202312,2,TO,10045,BRADESCO,18,"181262,13"
2100,202312,2,TO,52072,C6 BANK,4,"14493,26"
2101,202312,2,TO,51626,CAIXA ECONÔMICA FEDERAL,55,"98061,03"
2102,202312,2,TO,10069,ITAU,28,"71796,55"
2103,202312,2,TO,51011,VOTORANTIM,18,"98361,43"

### Encontrar linhas duplicadas com base na coluna uf organizando os dados###

In [62]:
# Parte nova implementada
# Encontrar linhas duplicadas com base na coluna video_id organizado
duplicidade = df[df.duplicated(subset='uf', keep=False)]

# Organizar pela coluna  nome
duplicidade.sort_values(by=['nome'])

,data_base,faixa,uf,cod_cng_fin,nome,qtd_operacoes,vol_operacoes
835,202311,1,AL,51750,BANCO SICOOB,6,"8657,50"
338,202310,1,MA,51750,BANCO SICOOB,1,"747,92"
1193,202311,1,SP,51750,BANCO SICOOB,90,"99537,08"
1588,202312,1,GO,51750,BANCO SICOOB,16,"21692,77"
1180,202311,1,SE,51750,BANCO SICOOB,1,"682,06"
...,...,...,...,...,...,...,...
624,202310,2,BA,51011,VOTORANTIM,63,"330710,10"
1113,202311,1,RN,51011,VOTORANTIM,38,"39334,18"
1922,202312,2,CE,51011,VOTORANTIM,116,"546869,73"
112,202309,2,PA,51011,VOTORANTIM,106,"974073,60"
2103,202312,2,TO,51011,VOTORANTIM,18,"98361,43"

In [63]:
# verificar o tamanho no dataframe
df.shape

(2104, 7)

In [ ]:
# Eliminando dados duplicados no dataframe via coluna video_id
#df = df.drop_duplicates(subset='video_id')

In [64]:
# Checagem
df.shape

(2104, 7)

In [65]:
# Checagem
print('A coluna nome possui valores unicos? Resposta: ', df.uf.is_unique)

A coluna nome possui valores unicos? Resposta:  False

In [66]:
# Mostrando nosso conjunto de dados
df.head()

,data_base,faixa,uf,cod_cng_fin,nome,qtd_operacoes,vol_operacoes
0,202309,2,AC,49906,BB,143,"1424098,33"
1,202309,2,AC,10045,BRADESCO,16,"110040,84"
2,202309,2,AC,49944,BTG PACTUAL,7,"37788,79"
3,202309,2,AC,51626,CAIXA ECONÔMICA FEDERAL,83,"248219,50"
4,202309,2,AC,51884,INTER,5,"16763,18"

### Eliminando colunas desnecessárioas em relação ao objetivo proposto###

> O parametro axis=1 indica que as colunas que informei devem ser eliminadas

> caso queira eliminar linhas, o parametro usado será axis=0

In [67]:
df.drop(['cod_cng_fin'], axis=1, inplace=True)

In [68]:
# Checagem
df.head()

   data_base  faixa  uf                     nome  qtd_operacoes vol_operacoes
0     202309      2  AC                       BB            143    1424098,33
1     202309      2  AC                 BRADESCO             16     110040,84
2     202309      2  AC              BTG PACTUAL              7      37788,79
3     202309      2  AC  CAIXA ECONÔMICA FEDERAL             83     248219,50
4     202309      2  AC                    INTER              5      16763,18